version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    networks:
      - backend
networks:
  backend: